version: "3.8"

services: # PHP Service
    php:
        container_name: php
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        env_file:
            - .env
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - .:/var/www:delegated
        ports:
            - "8000:8000"
        depends_on:
            - database
    # Node Server
    node:
        container_name: node
        build:
            context: .
            target: node
        volumes:
            - .:/var/www
            - ./node_modules:/var/www/node_modules
        depends_on:
            - php
        stdin_open: true
        tty: true

    # Database Server
    database:
        container_name: database
        image: mysql:8.2
        restart: on-failure
        ports:
            - "3306:3306"
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_USER=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - db-vol:/var/lib/mysql

volumes:
    db-vol: ~
