version: "3.8"
services:

    # PHP Service
    php:
        container_name: php
        build:
            context: .
            dockerfile: .docker/php/Dockerfile
            target: php
            args:
                - APP_ENV=${APP_ENV}
        env_file:
            - .env
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - .:/var/www:delegated
        ports:
            - 8000:8000
        depends_on:
            - database

    # Database Server
    database:
        container_name: database
        image: mysql:8.0
        restart: on-failure
        ports:
            - 3306:3306
        env_file:
            -   .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_USER=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - db-vol:/var/lib/mysql

    # Node Server
    node:
        container_name: node
        build:
            context: .
            dockerfile: .docker/node/Dockerfile
            target: node
        volumes:
            - .:/var/www
            - ./node_modules:/var/www/node_modules
        tty: true

volumes:
    db-vol: ~
