version: "3.8"
services:
    # PHP Server
    php:
        container_name: php
        build:
            context: .
            target: composer
            args:
                - APP_ENV=${APP_ENV}
        env_file:
            - .env
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        volumes:
            - .:/app
        ports:
            - 8000:8000
        depends_on:
            - database
    # Node Server
    node:
        container_name: node
        build:
            context: .
            target: composer
        volumes:
            - .:/var/www
            - ./node_modules:/var/www/node_modules
        depends_on:
            - php
        tty: true

    # Database Server
    database:
        container_name: database
        image: mysql:8.2
        restart: on-failure
        ports:
            - "3306:3306"
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_USER=${DB_USERNAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        volumes:
            - db-vol:/var/lib/mysql

    # Queue
#    queue:
#        container_name: Queue
#        build:
#            context: .
#            target: php
#        command: 'php artisan queue:work'
#        depends_on:
#            - database

    # Mailpit
    mailpit:
        image: axllent/mailpit
        container_name: MailPit
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - cookery-net
volumes:
    db-vol: ~

networks:
    cookery-net:
        driver: bridge

